-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 09:29:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bus_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus_company` DEFAULT CHARACTER SET utf8 ;
USE `bus_company` ;

-- -----------------------------------------------------
-- Table `bus_company`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`worker` (
  `worker_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sex` ENUM('男', '女') NOT NULL,
  `profession` ENUM('司机', '队长') NOT NULL,
  PRIMARY KEY (`worker_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`leader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`leader` (
  `worker_id` INT NOT NULL,
  INDEX `fk_leader_worker1_idx` (`worker_id` ASC) VISIBLE,
  PRIMARY KEY (`worker_id`),
  CONSTRAINT `fk_leader_worker1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `bus_company`.`worker` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`fleet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`fleet` (
  `fleet_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `leader_id` INT NOT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`fleet_id`),
  INDEX `fk_fleet_leader1_idx` (`leader_id` ASC) VISIBLE,
  CONSTRAINT `fk_fleet_leader1`
    FOREIGN KEY (`leader_id`)
    REFERENCES `bus_company`.`leader` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`line` (
  `line_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `fleet_id` INT NOT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`line_id`),
  INDEX `fk_line_fleet1_idx` (`fleet_id` ASC) VISIBLE,
  CONSTRAINT `fk_line_fleet1`
    FOREIGN KEY (`fleet_id`)
    REFERENCES `bus_company`.`fleet` (`fleet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`driver` (
  `worker_id` INT NOT NULL,
  `line_id` INT NOT NULL,
  INDEX `fk_driver_worker1_idx` (`worker_id` ASC) VISIBLE,
  PRIMARY KEY (`worker_id`),
  INDEX `fk_driver_line1_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_driver_worker1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `bus_company`.`worker` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_driver_line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `bus_company`.`line` (`line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`car` (
  `car_id` VARCHAR(45) NOT NULL,
  `line_id` INT NOT NULL,
  `seat` INT NOT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `fk_car_line1_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `bus_company`.`line` (`line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`violation_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`violation_record` (
  `violation_record_id` INT NOT NULL AUTO_INCREMENT,
  `driver_id` INT NOT NULL,
  `car_id` VARCHAR(45) NOT NULL,
  `type` ENUM('闯红灯', '未礼让斑马线', '压线', '违章停车') NOT NULL,
  `time` DATETIME NOT NULL,
  `port` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`violation_record_id`),
  INDEX `fk_violation_record_car1_idx` (`car_id` ASC) VISIBLE,
  INDEX `fk_violation_record_driver1_idx` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `fk_violation_record_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `bus_company`.`car` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_violation_record_driver1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `bus_company`.`driver` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_company`.`line_leader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_company`.`line_leader` (
  `worker_id` INT NOT NULL,
  INDEX `fk_line_leader_driver1_idx` (`worker_id` ASC) VISIBLE,
  PRIMARY KEY (`worker_id`),
  CONSTRAINT `fk_line_leader_driver1`
    FOREIGN KEY (`worker_id`)
    REFERENCES `bus_company`.`driver` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `bus_company`.`user` (
  `id` INT NOT NULL,
  `password` VARCHAR(450) NOT NULL,
  `job` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
